version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - .env2
    volumes:
    - db:/var/lib/postgresql/data/
    restart: always
  django_daphne:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_daphne
    restart: always

volumes:
  static:
  db:
