version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
  redis:
    image: redis
    command: redis-server
    expose:
      - 6379
  django_daphne:
    volumes:
      - static:/app/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - django_daphne

volumes:
  static:
  postgres_data: