version: "3.8"
services:
  backend:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    # stdin_open: true
    # tty: true
    # environment:
    #   - DJANGO_SETTINGS_MODULE=backend.settings
    # command: python3 manage.py runserver 0.0.0.0:8000
    # restart: always
volumes:
  static: