export const GAME_DETAILS_REQUEST = 'GAME_DETAILS_REQUEST'
export const GAME_DETAILS_SUCCESS = 'GAME_DETAILS_SUCCESS'
export const GAME_DETAILS_FAIL = 'GAME_DETAILS_FAIL'

export const GAME_NEXT_ROUND_REQUEST = 'GAME_NEXT_ROUND_REQUEST'
export const GAME_NEXT_ROUND_SUCCESS = 'GAME_NEXT_ROUND_SUCCESS'
export const GAME_NEXT_ROUND_FAIL = 'GAME_NEXT_ROUND_FAIL'
