export const POKER_STAGE_PREFLAP = 'POKER_STAGE_PREFLAP'
export const POKER_STAGE_FLAP = 'POKER_STAGE_FLAP'
export const POKER_STAGE_TURN = 'POKER_STAGE_TURN'
export const POKER_STAGE_RIVER = 'POKER_STAGE_RIVER'

