# Generated by Django 4.1.2 on 2023-02-12 18:50

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0017_remove_user_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', base.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nick_name', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, ''), (1, 'Fold'), (2, 'Check'), (3, 'Call'), (4, 'Raise'), (5, 'Allin')], default=0, null=True)),
                ('credit_total', models.IntegerField(default=1000, null=True)),
                ('turn', models.BooleanField(default=False)),
                ('dealer', models.BooleanField(default=False)),
                ('small', models.BooleanField(default=False)),
                ('big', models.BooleanField(default=False)),
                ('bet', models.IntegerField(default=0)),
                ('image', models.ImageField(default='/avatar1.webp', upload_to=base.models.upload_path)),
                ('card1', models.IntegerField(default=0)),
                ('card2', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('type', models.IntegerField(choices=[(0, 'Holdem-Texas'), (1, 'Omaha')], default=0)),
                ('max', models.IntegerField(choices=[(0, '3'), (1, '6'), (2, '9')], default=1)),
                ('min', models.IntegerField(default=0)),
                ('small', models.IntegerField(default=1, null=True)),
                ('isAvailable', models.BooleanField(default=True)),
                ('online', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('round', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('stage', models.IntegerField(choices=[(0, 'Preflap'), (1, 'Flap'), (2, 'Turn'), (3, 'River')], default=0)),
                ('turn', models.IntegerField(default=0, null=True)),
                ('changer', models.IntegerField(default=0, null=True)),
                ('small_blind', models.IntegerField(default=0, null=True)),
                ('bet', models.IntegerField(default=0, null=True)),
                ('pot', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('JSON_data', models.JSONField(default=base.models.data)),
                ('JSON_ground', models.JSONField(default=base.models.ground)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.table')),
                ('player', models.ManyToManyField(blank=True, to='base.player')),
            ],
        ),
    ]
