# Generated by Django 4.1.2 on 2023-01-26 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('round', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('bet', models.IntegerField(blank=True, null=True)),
                ('pot', models.IntegerField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(0, ''), (1, 'Fold'), (2, 'Check'), (3, 'Call'), (4, 'Raise'), (5, 'Allin')], default=0, null=True)),
                ('turn', models.BooleanField(default=False)),
                ('dealer', models.BooleanField(default=False)),
                ('small', models.BooleanField(default=False)),
                ('big', models.BooleanField(default=False)),
                ('bet', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('card1', models.IntegerField(blank=True, default=0)),
                ('card2', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('small', models.IntegerField(blank=True, null=True)),
                ('big', models.IntegerField(blank=True, null=True)),
                ('online', models.IntegerField(blank=True, null=True)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('waiting', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
