# Generated by Django 4.1.2 on 2023-02-12 17:32

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='/avatar1.webp', upload_to=base.models.upload_path),
        ),
    ]
