# Generated by Django 4.1.2 on 2023-02-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='online',
        ),
    ]
