# Generated by Django 4.1.2 on 2023-02-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_table_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isPlayed',
            field=models.BooleanField(default=False),
        ),
    ]
