# Generated by Django 4.1.2 on 2023-02-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_game_isplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
