# Generated by Django 4.1.2 on 2023-02-16 17:55

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_game_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameObject',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
