# Generated by Django 4.1.2 on 2023-01-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_game_table_player_user_alter_player_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='big',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='card1',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='card2',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='dealer',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='small',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.IntegerField(choices=[(0, ''), (1, 'Fold'), (2, 'Check'), (3, 'Call'), (4, 'Raise'), (5, 'Allin')], default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='turn',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
