# Generated by Django 4.1.2 on 2023-01-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_player_big_alter_player_card1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.table'),
        ),
        migrations.AlterField(
            model_name='player',
            name='big',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='card1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='card2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='small',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Fold'), (2, 'Check'), (3, 'Call'), (4, 'Raise'), (5, 'Allin')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='turn',
            field=models.BooleanField(default=False),
        ),
    ]
