# Generated by Django 4.1.2 on 2023-01-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='card1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='card2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
