# Generated by Django 4.1.2 on 2023-01-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_player_card1_alter_player_card2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
