# Generated by Django 4.1.2 on 2023-01-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_game_pot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='round',
            new_name='ID',
        ),
    ]
