# Generated by Django 4.1.2 on 2023-01-26 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_round_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='ID',
            new_name='round',
        ),
    ]
