# Generated by Django 4.1.2 on 2023-01-27 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_player_game_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.table'),
        ),
    ]
