# Generated by Django 4.1.2 on 2023-01-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_game_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(blank=True, to='base.player'),
        ),
    ]
