# Generated by Django 4.1.2 on 2023-01-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_game_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='state',
            new_name='status',
        ),
    ]
