# Generated by Django 4.1.2 on 2023-01-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_state_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='card1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='card2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='/img/avatar1.webp', null=True, upload_to=''),
        ),
    ]
