# Generated by Django 4.1.2 on 2023-01-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_player_card1_alter_player_card2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joinedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
