# Generated by Django 4.1.2 on 2023-01-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_player_joinedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='online',
        ),
    ]
