# Generated by Django 4.1.2 on 2023-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_table_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='credit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
