# Generated by Django 4.1.2 on 2023-01-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_player_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='credit',
            new_name='credit_total',
        ),
    ]
