# Generated by Django 4.1.2 on 2023-01-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_credit_player_credit_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='min',
            field=models.IntegerField(default=0),
        ),
    ]
