# Generated by Django 4.1.2 on 2023-01-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_table_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='isAvailable',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
