# Generated by Django 4.1.2 on 2023-01-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_table_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
