# Generated by Django 4.1.2 on 2023-01-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_table_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='online',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
