# Generated by Django 4.1.2 on 2023-01-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_table_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='leftAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='joinedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
