# Generated by Django 4.1.2 on 2023-01-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_player_balance_alter_player_bet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='card1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='card2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='card3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='card4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='card5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bet',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='dealer',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pot',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Preflap'), (1, 'Flap'), (2, 'Turn'), (3, 'River')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='card1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='card2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='/img/avatar1.webp', upload_to=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='joinedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='leftAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='table',
            name='online',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='small',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.IntegerField(choices=[(0, 'Holdem-Texas'), (1, 'Omaha')], default=0),
        ),
    ]
