# Generated by Django 4.1.2 on 2023-01-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_game_card1_game_card2_game_card3_game_card4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='leftAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
