# Generated by Django 4.1.2 on 2023-01-29 02:43

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_game_card1_remove_game_card2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ground',
            field=models.JSONField(default=base.models.ground),
        ),
    ]
