# Generated by Django 4.1.2 on 2023-01-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_createdat_game_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='ground',
            new_name='JSON_data',
        ),
    ]
