# Generated by Django 4.1.2 on 2023-01-29 14:13

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_rename_ground_game_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='JSON_data',
            field=models.JSONField(default=base.models.data),
        ),
    ]
