# Generated by Django 4.1.2 on 2023-01-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_game_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='changer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
