# Generated by Django 4.1.2 on 2023-02-04 11:52

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_game_json_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='JSON_ground',
            field=models.JSONField(default=base.models.ground),
        ),
    ]
